#ifndef ERROR_H
#define ERROR_H

#include <limits.h>

enum error {
  SUCCESS = 0,
  FAILURE = INT_MIN,
  SHADER_LINK_ERROR,
  SHADER_CREATE_ERROR,
  SHADER_FILE_ERROR, 
  SHADER_ATTRIBUTE_ERROR,
  SHADER_UNIFORM_UNKOWN_ERROR,
  SHADER_UNIFORM_SET_ERROR,
  SHADER_USE_ERROR,
  RENDERABLE_BUFFER_ERROR,
  RENDERABLE_RENDER_ERROR,
  MESH_LOAD_FILE_NOT_FOUND,
  MESH_LOAD_FILE_READ,
  TEXTURE_LOAD_ERROR,
};

#endif
